import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';

import '../../../../app/routes.dart';
import '../../../../app/theme/app_theme.dart';
import '../../../../core/errors/app_exception.dart';
import '../../../../core/formatters/indian_formatters.dart';
import '../../../../core/widgets/dk_empty.dart';
import '../../../../l10n/app_localizations.dart';
import '../providers/farm_providers.dart';

String _dateIso(DateTime d) {
  final local = DateTime(d.year, d.month, d.day);
  return '${local.year.toString().padLeft(4, '0')}-'
      '${local.month.toString().padLeft(2, '0')}-'
      '${local.day.toString().padLeft(2, '0')}';
}

DateTime _localDateOnly([DateTime? from]) {
  final n = from ?? DateTime.now();
  return DateTime(n.year, n.month, n.day);
}

bool _isCustomerNoMilk(Map<String, dynamic> d) {
  final status = '${d['status'] ?? ''}';
  if (status != 'SKIPPED') return false;
  final notes = '${d['deliveryNotes'] ?? d['delivery_notes'] ?? ''}';
  return notes.contains('Customer:');
}

/// One red card per customer per day when they asked for no milk.
List<Map<String, dynamic>> _collapseFarmDayRows(
    List<Map<String, dynamic>> rows) {
  final out = <Map<String, dynamic>>[];
  final seenNoMilk = <String>{};
  for (final d in rows) {
    if (!_isCustomerNoMilk(d)) {
      out.add(d);
      continue;
    }
    final key = '${d['customerId']}|${d['deliveryDate'] ?? ''}';
    if (seenNoMilk.contains(key)) continue;
    seenNoMilk.add(key);
    out.add(d);
  }
  return out;
}

final farmTodayDeliveriesProvider =
    FutureProvider.family<List<Map<String, dynamic>>, FarmDashboardDateRange>(
        (ref, range) async {
  return ref.watch(farmApiProvider).todayDeliveries(
        from: range.from,
        to: range.to,
      );
});

final farmDailyListStatusProvider =
    FutureProvider.family<Map<String, dynamic>, String>((ref, dateIso) async {
  final farmId = await ref.watch(currentFarmIdProvider.future);
  return ref.watch(farmApiProvider).dailyListStatus(farmId, date: dateIso);
});

class FarmTodayDeliveriesScreen extends ConsumerStatefulWidget {
  const FarmTodayDeliveriesScreen({super.key});

  @override
  ConsumerState<FarmTodayDeliveriesScreen> createState() =>
      _FarmTodayDeliveriesScreenState();
}

class _FarmTodayDeliveriesScreenState
    extends ConsumerState<FarmTodayDeliveriesScreen> {
  late FarmDashboardDateRange _range;
  final Set<String> _autoGeneratedFor = {};
  bool _busy = false;

  @override
  void initState() {
    super.initState();
    final t = _dateIso(_localDateOnly());
    _range = FarmDashboardDateRange(from: t, to: t);
    // Morning open: build today's list as soon as the home screen appears.
    WidgetsBinding.instance.addPostFrameCallback((_) {
      if (!mounted) return;
      ref.read(farmTodayDeliveriesProvider(_range).future).then((rows) {
        if (!mounted) return;
        _maybeAutoGenerate(rows);
      });
    });
  }

  String get _from => _range.from;
  String get _to => _range.to;
  bool get _isSingleDay => _range.isSingleDay;

  DateTime get _today => _localDateOnly();
  DateTime get _yesterday => _today.subtract(const Duration(days: 1));
  DateTime get _tomorrow => _today.add(const Duration(days: 1));
  DateTime get _weekEnd => _today.add(const Duration(days: 6));

  bool get _isToday {
    final t = _dateIso(_today);
    return _from == t && _to == t;
  }

  bool get _isYesterday {
    final y = _dateIso(_yesterday);
    return _from == y && _to == y;
  }

  bool get _isTomorrow {
    final t = _dateIso(_tomorrow);
    return _from == t && _to == t;
  }

  bool get _isThisWeek {
    return _from == _dateIso(_today) && _to == _dateIso(_weekEnd);
  }

  List<String> _daysInRange() {
    final start = DateTime.parse(_from);
    final end = DateTime.parse(_to);
    final days = <String>[];
    for (var d = start; !d.isAfter(end); d = d.add(const Duration(days: 1))) {
      days.add(_dateIso(d));
    }
    return days;
  }

  void _setDay(DateTime day) {
    final iso = _dateIso(_localDateOnly(day));
    setState(() => _range = FarmDashboardDateRange(from: iso, to: iso));
  }

  void _setThisWeek() {
    setState(
      () => _range = FarmDashboardDateRange(
        from: _dateIso(_today),
        to: _dateIso(_weekEnd),
      ),
    );
  }

  Future<void> _pickDate() async {
    final picked = await showDatePicker(
      context: context,
      initialDate: DateTime.parse(_from),
      firstDate: DateTime(2020),
      lastDate: _today.add(const Duration(days: 7)),
    );
    if (picked == null) return;
    _setDay(picked);
  }

  void _refreshTodayList() {
    if (!mounted) return;
    // Defer invalidate to next frame so we never dispose/rebuild while
    // watch/listen are mid-update (fixes `_dependents.isEmpty is not true`).
    WidgetsBinding.instance.addPostFrameCallback((_) {
      if (!mounted) return;
      ref.invalidate(farmTodayDeliveriesProvider(_range));
      ref.invalidate(farmDailyListStatusProvider(_from));
    });
  }

  Future<void> _toggleAutoGenerate(bool enabled) async {
    try {
      final farmId = await ref.read(currentFarmIdProvider.future);
      await ref.read(farmApiProvider).updateDeliverySettings(
            farmId,
            autoGenerateDailyList: enabled,
          );
      ref.invalidate(farmDailyListStatusProvider(_from));
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context)
            .showSnackBar(SnackBar(content: Text('$e')));
      }
    }
  }

  Future<void> _maybeAutoGenerate(List<Map<String, dynamic>> rows) async {
    if (!_isSingleDay) return;
    if (rows.isNotEmpty || _autoGeneratedFor.contains(_from) || _busy) return;
    final ok = await _generate(silent: true);
    if (ok) _autoGeneratedFor.add(_from);
  }

  Future<bool> _generate({bool silent = false}) async {
    if (_busy) return false;
    setState(() => _busy = true);
    try {
      final farmId = await ref.read(currentFarmIdProvider.future);
      final api = ref.read(farmApiProvider);
      final days = _isSingleDay ? [_from] : _daysInRange();
      var created = 0;
      var skipped = 0;
      for (final day in days) {
        final result = await api.generateDailyList(farmId, date: day);
        created += (result['created'] as num?)?.toInt() ?? 0;
        skipped += (result['skipped'] as num?)?.toInt() ?? 0;
      }
      _refreshTodayList();
      if (!silent && mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text(
              created == 0 && skipped == 0
                  ? 'No active customers due for this date. Check Customers / subscriptions.'
                  : 'Created $created; skipped $skipped',
            ),
          ),
        );
      } else if (silent && mounted && created == 0 && skipped == 0) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text(
              AppLocalizations.of(context).noDeliveriesTodayGenerateHint,
            ),
          ),
        );
      }
      return true;
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text(
              silent
                  ? AppLocalizations.of(context).couldNotBuildTodayList('$e')
                  : '$e',
            ),
          ),
        );
      }
      return false;
    } finally {
      if (mounted) setState(() => _busy = false);
    }
  }

  Future<void> _recordPaisa(String customerId) async {
    if (customerId.isEmpty) return;
    final result = await showDialog<({String amount, String purpose})>(
      context: context,
      builder: (_) => const _RecordCashDialog(),
    );
    if (result == null) return;
    final amount = result.amount;
    if (double.tryParse(amount) == null || double.parse(amount) <= 0) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
              content: Text(AppLocalizations.of(context).enterValidAmount)),
        );
      }
      return;
    }
    try {
      final farmId = await ref.read(currentFarmIdProvider.future);
      await ref.read(farmApiProvider).recordCashPayment(
            customerId: customerId,
            farmId: farmId,
            amount: amount,
            purpose: result.purpose,
            paymentDate: _from,
          );
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text(AppLocalizations.of(context).recordCash)),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context)
            .showSnackBar(SnackBar(content: Text('$e')));
      }
    }
  }

  Future<void> _diya(String id, String? qtyPrefill) async {
    if (_busy) return;
    setState(() => _busy = true);
    try {
      final controller = TextEditingController(text: qtyPrefill ?? '');
      final poured = await showDialog<String>(
        context: context,
        builder: (ctx) {
          final l10n = AppLocalizations.of(ctx);
          return AlertDialog(
            title: Text(l10n.farmDiya),
            content: Column(
              mainAxisSize: MainAxisSize.min,
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  qtyPrefill == null || qtyPrefill.isEmpty
                      ? 'Enter total litres poured. Less than the daily need is OK when milk is short — customer is charged only for what was poured. More than need is saved as extra.'
                      : 'Daily need $qtyPrefill L. Enter what you actually poured (e.g. 0.5 if milk is short). Charged only for poured litres; more than need = extra.',
                  style: TextStyle(
                    color: Dk.of(ctx).muted,
                    fontSize: 13,
                  ),
                ),
                const SizedBox(height: 12),
                TextField(
                  controller: controller,
                  keyboardType:
                      const TextInputType.numberWithOptions(decimal: true),
                  decoration: InputDecoration(
                    labelText: l10n.quantityL,
                  ),
                  autofocus: true,
                ),
              ],
            ),
            actions: [
              TextButton(
                onPressed: () => Navigator.pop(ctx),
                child: Text(l10n.cancel),
              ),
              FilledButton(
                onPressed: () => Navigator.pop(ctx, controller.text.trim()),
                child: Text(l10n.confirm),
              ),
            ],
          );
        },
      );
      final qty = poured;
      WidgetsBinding.instance.addPostFrameCallback((_) => controller.dispose());
      if (qty == null || qty.isEmpty) return;
      await ref.read(farmApiProvider).markDelivered(
            id,
            finalDeliveredQuantity: qty,
          );
      _refreshTodayList();
      try {
        await ref.read(farmTodayDeliveriesProvider(_range).future);
      } catch (_) {}
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context)
            .showSnackBar(SnackBar(content: Text('$e')));
      }
    } finally {
      if (mounted) setState(() => _busy = false);
    }
  }

  String _extraPrefill(String raw) {
    final n = double.tryParse(raw.replaceAll(',', '.')) ?? 0;
    if (n == n.roundToDouble()) return '${n.toInt()}';
    return n.toString();
  }

  Future<void> _addExtra(String id, {required String currentStaffExtra}) async {
    if (_busy) return;
    final extra = await showDialog<String>(
      context: context,
      builder: (ctx) =>
          _StaffExtraDialog(initial: _extraPrefill(currentStaffExtra)),
    );
    if (extra == null) return;
    if (extra.isEmpty) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
              content: Text(AppLocalizations.of(context).enterValidQuantity)),
        );
      }
      return;
    }
    final normalized = extra.replaceAll(',', '.');
    final parsed = double.tryParse(normalized);
    if (parsed == null || parsed < 0) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
              content: Text(AppLocalizations.of(context).enterValidQuantity)),
        );
      }
      return;
    }
    final qty = parsed == parsed.roundToDouble()
        ? '${parsed.toInt()}'
        : parsed.toStringAsFixed(3);
    setState(() => _busy = true);
    try {
      await ref.read(farmApiProvider).addExtra(
            id,
            extraQuantity: qty,
            replace: true,
          );
      _refreshTodayList();
      try {
        await ref.read(farmTodayDeliveriesProvider(_range).future);
      } catch (_) {}
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text(
              AppLocalizations.of(context).extraSetTapDiya(formatLitresString(qty)),
            ),
            backgroundColor: AppColors.leaf,
          ),
        );
      }
    } catch (e) {
      if (mounted) {
        final msg = e is AppException ? e.message : '$e';
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text(msg),
            backgroundColor: AppColors.danger,
          ),
        );
      }
    } finally {
      if (mounted) setState(() => _busy = false);
    }
  }

  Future<void> _quickAction(String id, String action) async {
    if (_busy) return;
    setState(() => _busy = true);
    try {
      final api = ref.read(farmApiProvider);
      switch (action) {
        case 'out':
          await api.outForDelivery(id);
        case 'skip':
          await api.skipDelivery(id);
        case 'fail':
          await api.failDelivery(id);
      }
      _refreshTodayList();
      try {
        await ref.read(farmTodayDeliveriesProvider(_range).future);
      } catch (_) {}
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context)
            .showSnackBar(SnackBar(content: Text('$e')));
      }
    } finally {
      if (mounted) setState(() => _busy = false);
    }
  }

  Future<void> _cantDeliverToday(
      {String? customerId, String? customerName}) async {
    if (_busy) return;
    if (!_isSingleDay) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text(
                AppLocalizations.of(context).pickSingleDayToCancel),
          ),
        );
      }
      return;
    }
    final forOne = customerId != null && customerId.isNotEmpty;
    final dayLabel = _dateChipLabel();
    final ok = await showDialog<bool>(
      context: context,
      builder: (ctx) => AlertDialog(
        title: Text(forOne
            ? AppLocalizations.of(context).cantDeliverToCustomerTitle
            : 'Can’t deliver on $dayLabel?'),
        content: Text(
          forOne
              ? 'We’ll notify ${customerName ?? 'this customer'} that milk won’t be delivered on $dayLabel.'
              : 'We’ll skip all open deliveries for $dayLabel and notify every customer.',
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(ctx, false),
            child: Text(AppLocalizations.of(context).keepDeliveries),
          ),
          FilledButton(
            style: FilledButton.styleFrom(backgroundColor: AppColors.danger),
            onPressed: () => Navigator.pop(ctx, true),
            child: Text(AppLocalizations.of(context).confirm),
          ),
        ],
      ),
    );
    if (ok != true || !mounted) return;
    setState(() => _busy = true);
    try {
      final farmId = await ref.read(currentFarmIdProvider.future);
      final api = ref.read(farmApiProvider);
      final result = await api.skipTodayDeliveries(
        farmId,
        customerId: customerId,
        date: _from,
      );
      _refreshTodayList();
      try {
        await ref.read(farmTodayDeliveriesProvider(_range).future);
      } catch (_) {}
      if (mounted) {
        final n = result['skipped'] ?? 0;
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text(
              AppLocalizations.of(context).notifiedCustomersSkipped('$n'),
            ),
          ),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('$e'), backgroundColor: AppColors.danger),
        );
      }
    } finally {
      if (mounted) setState(() => _busy = false);
    }
  }

  String? _lastGeneratedLabel(Map<String, dynamic>? status) {
    final raw = status?['lastGeneratedAt']?.toString();
    if (raw == null || raw.isEmpty) return null;
    final parsed = DateTime.tryParse(raw);
    if (parsed == null) return raw;
    return formatDateTime(parsed.toLocal());
  }

  String _dateChipLabel() {
    final l10n = AppLocalizations.of(context);
    if (_isToday) return l10n.datesToday;
    if (_isYesterday) return l10n.datesYesterday;
    if (_isTomorrow) return l10n.datesTomorrow;
    if (_isThisWeek) return l10n.datesThisWeek;
    if (_isSingleDay) return formatDate(DateTime.parse(_from));
    return '${formatDate(DateTime.parse(_from))} – ${formatDate(DateTime.parse(_to))}';
  }

  Future<void> _openDaySheet() async {
    await showModalBottomSheet<void>(
      context: context,
      showDragHandle: true,
      builder: (ctx) {
        final l10n = AppLocalizations.of(context);
        final options = <({String id, String label, VoidCallback apply})>[
          (
            id: 'today',
            label: l10n.datesToday,
            apply: () => _setDay(_today),
          ),
          (
            id: 'tomorrow',
            label: l10n.datesTomorrow,
            apply: () => _setDay(_tomorrow),
          ),
          (
            id: 'week',
            label: l10n.datesThisWeek,
            apply: _setThisWeek,
          ),
          (
            id: 'yesterday',
            label: l10n.datesYesterday,
            apply: () => _setDay(_yesterday),
          ),
        ];
        String? selectedId;
        if (_isToday) selectedId = 'today';
        if (_isTomorrow) selectedId = 'tomorrow';
        if (_isThisWeek) selectedId = 'week';
        if (_isYesterday) selectedId = 'yesterday';

        return SafeArea(
          child: Padding(
            padding: const EdgeInsets.fromLTRB(8, 0, 8, 16),
            child: Column(
              mainAxisSize: MainAxisSize.min,
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [
                Padding(
                  padding: const EdgeInsets.fromLTRB(16, 4, 16, 8),
                  child: Text(
                    l10n.selectDay,
                    style: Theme.of(ctx).textTheme.titleMedium?.copyWith(
                          fontWeight: FontWeight.w700,
                        ),
                  ),
                ),
                for (final o in options)
                  ListTile(
                    leading: Icon(
                      selectedId == o.id
                          ? Icons.radio_button_checked
                          : Icons.radio_button_off,
                      color: selectedId == o.id
                          ? AppColors.leaf
                          : Dk.of(ctx).muted,
                    ),
                    title: Text(o.label),
                    onTap: () {
                      o.apply();
                      Navigator.pop(ctx);
                    },
                  ),
                ListTile(
                  leading: Icon(
                    selectedId == null
                        ? Icons.radio_button_checked
                        : Icons.radio_button_off,
                    color:
                        selectedId == null ? AppColors.leaf : Dk.of(ctx).muted,
                  ),
                  title: Text(l10n.pickDate),
                  subtitle: selectedId == null && _isSingleDay
                      ? Text(formatDate(DateTime.parse(_from)))
                      : Text(AppLocalizations.of(context).chooseAnyDay),
                  onTap: () async {
                    Navigator.pop(ctx);
                    await _pickDate();
                  },
                ),
              ],
            ),
          ),
        );
      },
    );
  }

  @override
  Widget build(BuildContext context) {
    final l10n = AppLocalizations.of(context);
    final deliveriesAsync = ref.watch(farmTodayDeliveriesProvider(_range));
    final statusAsync = ref.watch(farmDailyListStatusProvider(_from));

    ref.listen(farmTodayDeliveriesProvider(_range), (prev, next) {
      if (_busy) return;
      next.whenData(_maybeAutoGenerate);
    });

    // Shell already owns the main AppBar — no nested header / back arrow.
    return Column(
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: [
        Padding(
          padding: const EdgeInsets.fromLTRB(16, 12, 16, 0),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              Text(
                l10n.day,
                style: TextStyle(
                  color: Dk.of(context).muted,
                  fontSize: 13,
                  fontWeight: FontWeight.w600,
                ),
              ),
              const SizedBox(height: 8),
              Material(
                color: Dk.of(context).milkWhite,
                borderRadius: BorderRadius.circular(12),
                child: InkWell(
                  borderRadius: BorderRadius.circular(12),
                  onTap: _openDaySheet,
                  child: Padding(
                    padding: const EdgeInsets.symmetric(
                      horizontal: 14,
                      vertical: 12,
                    ),
                    child: Row(
                      children: [
                        Icon(Icons.date_range, color: AppColors.leaf, size: 20),
                        const SizedBox(width: 10),
                        Expanded(
                          child: Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Text(
                                _dateChipLabel(),
                                style: TextStyle(
                                  fontWeight: FontWeight.w700,
                                  color: Dk.of(context).ink,
                                ),
                              ),
                              Text(
                                _isSingleDay
                                    ? formatDate(DateTime.parse(_from))
                                    : '${formatDate(DateTime.parse(_from))} – ${formatDate(DateTime.parse(_to))}',
                                style: TextStyle(
                                  color: Dk.of(context).muted,
                                  fontSize: 13,
                                ),
                              ),
                            ],
                          ),
                        ),
                        Icon(Icons.expand_more, color: Dk.of(context).muted),
                      ],
                    ),
                  ),
                ),
              ),
              const SizedBox(height: 10),
              Row(
                children: [
                  Expanded(
                    child: OutlinedButton(
                      onPressed: _busy ? null : () => _generate(),
                      child: Text(l10n.generate),
                    ),
                  ),
                  const SizedBox(width: 8),
                  Expanded(
                    child: OutlinedButton(
                      onPressed: _busy ? null : () => _cantDeliverToday(),
                      style: OutlinedButton.styleFrom(
                        foregroundColor: AppColors.danger,
                        side: const BorderSide(color: AppColors.danger),
                      ),
                      child: Text(l10n.cantDeliver),
                    ),
                  ),
                ],
              ),
            ],
          ),
        ),
        Padding(
          padding: const EdgeInsets.fromLTRB(16, 8, 16, 0),
          child: Text(
            _isSingleDay
                ? AppLocalizations.of(context).fullDayLabel(_dateChipLabel())
                : 'Schedule · ${_dateChipLabel()}',
            style: TextStyle(color: Dk.of(context).muted, fontSize: 13),
          ),
        ),
        Expanded(
          child: RefreshIndicator(
            onRefresh: () async {
              _refreshTodayList();
              await ref.read(farmTodayDeliveriesProvider(_range).future);
            },
            child: deliveriesAsync.when(
              data: (rawRows) {
                final rows = _collapseFarmDayRows(rawRows);
                final status = statusAsync.asData?.value;
                final generated = status?['generated'] == true;
                final autoOn = status?['autoGenerateDailyList'] != false;
                final lastLabel = _lastGeneratedLabel(status);
                final showBanner = status != null ? !generated : rows.isEmpty;

                return ListView(
                  padding: const EdgeInsets.all(16),
                  children: [
                    if (status != null) ...[
                      SwitchListTile(
                        contentPadding: EdgeInsets.zero,
                        title: Text(
                          AppLocalizations.of(context).autoGenerateDailyList,
                          style: TextStyle(
                            color: Dk.of(context).ink,
                            fontWeight: FontWeight.w600,
                          ),
                        ),
                        subtitle: Text(
                          lastLabel != null
                              ? 'Last generated $lastLabel'
                              : 'Not generated yet for this date',
                          style: TextStyle(color: Dk.of(context).muted),
                        ),
                        value: autoOn,
                        onChanged: _busy ? null : (v) => _toggleAutoGenerate(v),
                      ),
                      const SizedBox(height: 8),
                    ],
                    if (showBanner)
                      Material(
                        color: AppColors.warning.withValues(alpha: 0.12),
                        borderRadius: BorderRadius.circular(12),
                        child: Padding(
                          padding: const EdgeInsets.all(14),
                          child: Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Text(
                                AppLocalizations.of(context).noDeliveryListYet,
                                style: TextStyle(
                                  fontWeight: FontWeight.w700,
                                  color: Dk.of(context).ink,
                                ),
                              ),
                              const SizedBox(height: 4),
                              Text(
                                AppLocalizations.of(context).tapGenerateListHint +
                                    (autoOn
                                        ? ' Or wait for morning auto-generate.'
                                        : ''),
                                style: TextStyle(color: Dk.of(context).muted),
                              ),
                              const SizedBox(height: 10),
                              FilledButton(
                                onPressed: _busy ? null : () => _generate(),
                                child: Text(l10n.generateList),
                              ),
                            ],
                          ),
                        ),
                      ),
                    if (showBanner) const SizedBox(height: 16),
                    if (rows.isEmpty)
                      DkEmpty(
                        message:
                            AppLocalizations.of(context).noCustomersToDeliver,
                        actionLabel: 'Generate list',
                        onAction: _busy ? null : () => _generate(),
                      )
                    else ...[
                      if (rows.any(_isCustomerNoMilk))
                        Padding(
                          padding: const EdgeInsets.only(bottom: 12),
                          child: Material(
                            color: AppColors.danger.withValues(alpha: 0.12),
                            borderRadius: BorderRadius.circular(12),
                            child: Padding(
                              padding: const EdgeInsets.all(12),
                              child: Text(
                                AppLocalizations.of(context).customersDontWantMilk('${rows.where(_isCustomerNoMilk).length}', _isSingleDay ? _dateChipLabel() : AppLocalizations.of(context).datesThisWeek),
                                style: const TextStyle(
                                  color: AppColors.danger,
                                  fontWeight: FontWeight.w700,
                                ),
                              ),
                            ),
                          ),
                        ),
                      for (final day in () {
                        final map = <String, List<Map<String, dynamic>>>{};
                        for (final d in rows) {
                          final key = '${d['deliveryDate'] ?? _from}';
                          map.putIfAbsent(key, () => []).add(d);
                        }
                        final keys = map.keys.toList()..sort();
                        return keys.map((k) {
                          final list = map[k]!;
                          list.sort((a, b) {
                            final an = _isCustomerNoMilk(a) ? 0 : 1;
                            final bn = _isCustomerNoMilk(b) ? 0 : 1;
                            return an.compareTo(bn);
                          });
                          return MapEntry(k, list);
                        });
                      }()) ...[
                        if (!_isSingleDay)
                          Padding(
                            padding: const EdgeInsets.only(top: 8, bottom: 8),
                            child: Text(
                              formatDate(DateTime.parse(day.key)),
                              style: TextStyle(
                                fontWeight: FontWeight.w800,
                                color: Dk.of(context).ink,
                                fontSize: 15,
                              ),
                            ),
                          ),
                        ...day.value.map((d) {
                          final id = '${d['id']}';
                          final statusCode = '${d['status'] ?? ''}';
                          final customerNoMilk = _isCustomerNoMilk(d);
                          final rowDay = '${d['deliveryDate'] ?? _from}';
                          final scheduled = double.tryParse(
                                  '${d['scheduledQuantity'] ?? 0}') ??
                              0;
                          final customerExtraQty = double.tryParse(
                                '${d['customerExtraQuantity'] ?? 0}',
                              ) ??
                              0;
                          // Diya default = daily need only. Staff extra is set by
                          // typing more than need (or the Extra button) — not by
                          // confirming a prefilled 1+extra total.
                          final qtyPrefill = formatQuantityString(
                            (scheduled + customerExtraQty).toString(),
                          );
                          final customerId = '${d['customerId'] ?? ''}';
                          final canAct = statusCode == 'PENDING' ||
                              statusCode == 'OUT_FOR_DELIVERY';
                          final canAddExtra = statusCode == 'PENDING' ||
                              statusCode == 'OUT_FOR_DELIVERY' ||
                              statusCode == 'DELIVERED';
                          final staffExtra =
                              '${d['staffExtraQuantity'] ?? '0'}';
                          final custExtra =
                              '${d['customerExtraQuantity'] ?? '0'}';
                          final extraTotal =
                              (double.tryParse(staffExtra) ?? 0) +
                                  (double.tryParse(custExtra) ?? 0);
                          final qtyDisplay = statusCode == 'DELIVERED'
                              ? '${d['finalDeliveredQuantity'] ?? d['quantity'] ?? d['scheduledQuantity'] ?? ''}'
                              : '${d['expectedQuantity'] ?? d['scheduledQuantity'] ?? ''}';
                          return Container(
                            margin: const EdgeInsets.only(bottom: 10),
                            decoration: BoxDecoration(
                              color: customerNoMilk
                                  ? AppColors.danger.withValues(alpha: 0.1)
                                  : Dk.of(context).milkWhite,
                              borderRadius: BorderRadius.circular(12),
                              border: customerNoMilk
                                  ? Border.all(color: AppColors.danger)
                                  : null,
                            ),
                            child: Material(
                              color: Colors.transparent,
                              child: InkWell(
                                borderRadius: BorderRadius.circular(12),
                                onTap: customerId.isEmpty
                                    ? null
                                    : () => context.push(
                                          AppRoutes.farmTodayCustomer(
                                            customerId,
                                            date: rowDay,
                                          ),
                                        ),
                                child: Padding(
                                  padding: const EdgeInsets.all(14),
                                  child: Column(
                                    crossAxisAlignment:
                                        CrossAxisAlignment.start,
                                    children: [
                                      Row(
                                        children: [
                                          Expanded(
                                            child: Text(
                                              '${d['customerName'] ?? 'Customer'}',
                                              style: TextStyle(
                                                fontWeight: FontWeight.w700,
                                                fontSize: 16,
                                                color: customerNoMilk
                                                    ? AppColors.danger
                                                    : null,
                                              ),
                                            ),
                                          ),
                                          if (customerNoMilk) ...[
                                            Chip(
                                              label: Text(
                                                AppLocalizations.of(context).noMilk,
                                                style: const TextStyle(
                                                  fontSize: 11,
                                                  color: AppColors.danger,
                                                  fontWeight: FontWeight.w700,
                                                ),
                                              ),
                                              visualDensity:
                                                  VisualDensity.compact,
                                              backgroundColor: Colors.white,
                                            ),
                                            const SizedBox(width: 6),
                                          ] else ...[
                                            if (customerId.isEmpty ||
                                                d['customerUserId'] == null ||
                                                '${d['customerUserId']}' ==
                                                    'null' ||
                                                '${d['customerUserId']}'
                                                    .isEmpty) ...[
                                              Chip(
                                                label: Text(l10n.managed),
                                                visualDensity:
                                                    VisualDensity.compact,
                                                labelStyle: const TextStyle(
                                                    fontSize: 11),
                                                backgroundColor:
                                                    Dk.of(context).foam,
                                              ),
                                              const SizedBox(width: 6),
                                            ],
                                            Chip(
                                              label: Text(statusCode,
                                                  style: const TextStyle(
                                                      fontSize: 11)),
                                              visualDensity:
                                                  VisualDensity.compact,
                                              backgroundColor:
                                                  Dk.of(context).foam,
                                            ),
                                          ],
                                          if (canAct)
                                            PopupMenuButton<String>(
                                              onSelected: (a) {
                                                if (a == 'cant') {
                                                  _cantDeliverToday(
                                                    customerId:
                                                        customerId.isEmpty
                                                            ? null
                                                            : customerId,
                                                    customerName:
                                                        '${d['customerName'] ?? 'Customer'}',
                                                  );
                                                } else {
                                                  _quickAction(id, a);
                                                }
                                              },
                                              itemBuilder: (_) => [
                                                PopupMenuItem(
                                                  value: 'cant',
                                                  child: Text(l10n.cantDeliver),
                                                ),
                                                PopupMenuItem(
                                                  value: 'fail',
                                                  child: Text(l10n.fail),
                                                ),
                                              ],
                                            ),
                                        ],
                                      ),
                                      if (customerNoMilk) ...[
                                        const SizedBox(height: 6),
                                        Text(AppLocalizations.of(context).customerDoesNotWantMilk,
                                          style: TextStyle(
                                            color: AppColors.danger,
                                            fontWeight: FontWeight.w600,
                                            fontSize: 13,
                                          ),
                                        ),
                                      ],
                                      const SizedBox(height: 4),
                                      Text(
                                        [
                                          formatLitresString(qtyDisplay),
                                          '${d['deliveryShift'] ?? ''}',
                                          if ('${d['productName'] ?? ''}'
                                              .isNotEmpty)
                                            '${d['productName']}',
                                          if ((double.tryParse(
                                                    '${d['ratePerLitre'] ?? ''}',
                                                  ) ??
                                                  0) >
                                              0)
                                            '${formatRupees(num.tryParse('${d['ratePerLitre']}') ?? 0)}/L',
                                          if (extraTotal > 0)
                                            'Extra ${formatLitresString(extraTotal.toString())}',
                                        ]
                                            .where((s) => s.trim().isNotEmpty)
                                            .join(' · '),
                                        style: TextStyle(
                                          fontWeight: FontWeight.w600,
                                          color: customerNoMilk
                                              ? AppColors.danger
                                              : null,
                                        ),
                                      ),
                                      if ((d['mobileNumber'] ?? '')
                                          .toString()
                                          .isNotEmpty)
                                        Text('${d['mobileNumber']}',
                                            style: TextStyle(
                                                color: Dk.of(context).muted)),
                                      if (canAct || canAddExtra) ...[
                                        const SizedBox(height: 12),
                                        Wrap(
                                          spacing: 8,
                                          runSpacing: 8,
                                          crossAxisAlignment:
                                              WrapCrossAlignment.center,
                                          children: [
                                            if (statusCode == 'PENDING')
                                              OutlinedButton(
                                                onPressed: _busy
                                                    ? null
                                                    : () =>
                                                        _quickAction(id, 'out'),
                                                style: OutlinedButton.styleFrom(
                                                  visualDensity:
                                                      VisualDensity.compact,
                                                  minimumSize:
                                                      const Size(56, 48),
                                                  tapTargetSize:
                                                      MaterialTapTargetSize
                                                          .shrinkWrap,
                                                ),
                                                child: Text(l10n.out),
                                              ),
                                            if (canAddExtra)
                                              OutlinedButton(
                                                onPressed: _busy
                                                    ? null
                                                    : () => _addExtra(
                                                          id,
                                                          currentStaffExtra:
                                                              staffExtra,
                                                        ),
                                                style: OutlinedButton.styleFrom(
                                                  visualDensity:
                                                      VisualDensity.compact,
                                                  minimumSize:
                                                      const Size(56, 48),
                                                  tapTargetSize:
                                                      MaterialTapTargetSize
                                                          .shrinkWrap,
                                                ),
                                                child: Text(l10n.extra),
                                              ),
                                            if (canAct)
                                              FilledButton(
                                                onPressed: _busy
                                                    ? null
                                                    : () => _diya(
                                                          id,
                                                          qtyPrefill == '—'
                                                              ? null
                                                              : qtyPrefill,
                                                        ),
                                                style: FilledButton.styleFrom(
                                                  backgroundColor:
                                                      AppColors.leaf,
                                                  minimumSize:
                                                      const Size(120, 48),
                                                  padding: const EdgeInsets
                                                      .symmetric(
                                                    horizontal: 16,
                                                    vertical: 14,
                                                  ),
                                                ),
                                                child: Text(
                                                  l10n.farmDiya,
                                                  style: const TextStyle(
                                                    fontSize: 16,
                                                    fontWeight: FontWeight.w800,
                                                  ),
                                                ),
                                              ),
                                            if (statusCode == 'DELIVERED' &&
                                                customerId.isNotEmpty)
                                              OutlinedButton(
                                                onPressed: _busy
                                                    ? null
                                                    : () => _recordPaisa(
                                                        customerId),
                                                style: OutlinedButton.styleFrom(
                                                  visualDensity:
                                                      VisualDensity.compact,
                                                  minimumSize:
                                                      const Size(56, 48),
                                                  tapTargetSize:
                                                      MaterialTapTargetSize
                                                          .shrinkWrap,
                                                ),
                                                child: Text(l10n.farmPaisaLiya),
                                              ),
                                          ],
                                        ),
                                      ],
                                    ],
                                  ),
                                ),
                              ),
                            ),
                          );
                        }),
                      ],
                    ],
                  ],
                );
              },
              loading: () => const Center(child: CircularProgressIndicator()),
              error: (e, _) => DkEmpty(
                message: '${AppLocalizations.of(context).couldNotLoad}.\n$e',
                actionLabel: 'Retry',
                onAction: () =>
                    ref.invalidate(farmTodayDeliveriesProvider(_range)),
              ),
            ),
          ),
        ),
      ],
    );
  }
}

/// Owns the [TextEditingController] so Cancel/Save never dispose it while the
/// dialog route is still animating out (that painted the red error screen).
class _StaffExtraDialog extends StatefulWidget {
  const _StaffExtraDialog({required this.initial});

  final String initial;

  @override
  State<_StaffExtraDialog> createState() => _StaffExtraDialogState();
}

class _StaffExtraDialogState extends State<_StaffExtraDialog> {
  late final TextEditingController _controller =
      TextEditingController(text: widget.initial);

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return AlertDialog(
      title: Text(AppLocalizations.of(context).extraMilk),
      content: TextField(
        controller: _controller,
        keyboardType: const TextInputType.numberWithOptions(decimal: true),
        decoration: InputDecoration(
          labelText: AppLocalizations.of(context).quantityL,
          helperText: AppLocalizations.of(context).replacesStaffExtra,
        ),
        autofocus: true,
      ),
      actions: [
        TextButton(
          onPressed: () => Navigator.pop(context),
          child: Text(AppLocalizations.of(context).cancel),
        ),
        FilledButton(
          onPressed: () => Navigator.pop(context, _controller.text.trim()),
          child: Text(AppLocalizations.of(context).save),
        ),
      ],
    );
  }
}

class _RecordCashDialog extends StatefulWidget {
  const _RecordCashDialog();

  @override
  State<_RecordCashDialog> createState() => _RecordCashDialogState();
}

class _RecordCashDialogState extends State<_RecordCashDialog> {
  final _amount = TextEditingController();
  String _purpose = 'BILL_PAYMENT';

  @override
  void dispose() {
    _amount.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final l10n = AppLocalizations.of(context);
    return AlertDialog(
      title: Text(l10n.farmPaisaLiya),
      content: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          TextField(
            controller: _amount,
            keyboardType: const TextInputType.numberWithOptions(decimal: true),
            decoration: InputDecoration(labelText: l10n.amountInr),
            autofocus: true,
          ),
          const SizedBox(height: 12),
          DropdownButtonFormField<String>(
            // Uncontrolled FormField: do not setState on change (avoids the old
            // initialValue rebuild bug and the deprecated `value` parameter).
            initialValue: _purpose,
            decoration: InputDecoration(labelText: AppLocalizations.of(context).purpose),
            items: [
              DropdownMenuItem(
                value: 'BILL_PAYMENT',
                child: Text(AppLocalizations.of(context).billPayment),
              ),
              DropdownMenuItem(
                value: 'ADVANCE_PAYMENT',
                child: Text(l10n.advance),
              ),
            ],
            onChanged: (v) {
              if (v != null) _purpose = v;
            },
          ),
        ],
      ),
      actions: [
        TextButton(
          onPressed: () => Navigator.pop(context),
          child: Text(l10n.cancel),
        ),
        FilledButton(
          onPressed: () {
            final amount = _amount.text.trim();
            if (amount.isEmpty) {
              Navigator.pop(context);
              return;
            }
            Navigator.pop(context, (amount: amount, purpose: _purpose));
          },
          child: Text(l10n.submit),
        ),
      ],
    );
  }
}
